import { Service, Stylist, GalleryItem, Review } from "./types";

// ─── All real Multicut Salon services ────────────────────────────────────────
export const fallbackServices: Service[] = [
  // ── Hair Cuts ──────────────────────────────────────────────────────────────
  { id: "1",  name: "Haircut",          slug: "haircut",          category: "Hair Cuts", price: 120, duration: 30, description: "Precision haircut styled to suit your face shape.", image_url: "https://images.unsplash.com/photo-1622288432450-277d0fef5ed6?w=600&q=80", featured: true,  sort_order: 1  },
  { id: "2",  name: "Baby Haircut",     slug: "baby-haircut",     category: "Hair Cuts", price: 100, duration: 20, description: "Gentle, careful haircut for little ones.",           image_url: "https://images.unsplash.com/photo-1622288432450-277d0fef5ed6?w=600&q=80", featured: false, sort_order: 2  },
  { id: "3",  name: "Old Age Haircut",  slug: "old-age-haircut",  category: "Hair Cuts", price: 100, duration: 30, description: "Comfortable haircut with extra care and patience.",   image_url: "https://images.unsplash.com/photo-1622288432450-277d0fef5ed6?w=600&q=80", featured: false, sort_order: 3  },

  // ── Beard & Shave ──────────────────────────────────────────────────────────
  { id: "4",  name: "Beard Trim",       slug: "beard-trim",       category: "Beard & Shave", price: 80, duration: 20, description: "Clean beard shaping and trim to define your look.", image_url: "https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=600&q=80", featured: true,  sort_order: 4  },
  { id: "5",  name: "Shave",            slug: "shave",            category: "Beard & Shave", price: 80, duration: 20, description: "Classic straight-razor shave for a smooth finish.",  image_url: "https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=600&q=80", featured: false, sort_order: 5  },

  // ── Hair Wash & Head Massage ───────────────────────────────────────────────
  { id: "6",  name: "Head Wash",                slug: "head-wash",                category: "Hair Wash & Head Massage", price: 20,  duration: 15, description: "Thorough cleansing wash for a fresh scalp.",            image_url: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80", featured: false, sort_order: 6  },
  { id: "7",  name: "Head Massage – Olive Oil", slug: "head-massage-olive-oil",   category: "Hair Wash & Head Massage", price: 150, duration: 30, description: "Deeply relaxing scalp massage with warm olive oil.",   image_url: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80", featured: false, sort_order: 7  },
  { id: "8",  name: "Head Massage – Almond Oil",slug: "head-massage-almond-oil",  category: "Hair Wash & Head Massage", price: 100, duration: 30, description: "Nourishing almond oil massage to strengthen roots.",    image_url: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80", featured: false, sort_order: 8  },
  { id: "9",  name: "Head Steam",               slug: "head-steam",               category: "Hair Wash & Head Massage", price: 50,  duration: 15, description: "Steam therapy to open pores and boost scalp health.", image_url: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80", featured: false, sort_order: 9  },

  // ── Hair Spa ───────────────────────────────────────────────────────────────
  { id: "10", name: "Hair Spa – Matrix",                  slug: "hair-spa-matrix",                  category: "Hair Spa", price: 250, duration: 45, description: "Revitalising Matrix spa treatment for deep nourishment.",         image_url: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80", featured: false, sort_order: 10 },
  { id: "11", name: "Hair Spa – Matrix Treatment",        slug: "hair-spa-matrix-treatment",        category: "Hair Spa", price: 300, duration: 60, description: "Advanced Matrix treatment spa for damaged and dry hair.",        image_url: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80", featured: false, sort_order: 11 },
  { id: "12", name: "Hair Spa – L'Oréal",                 slug: "hair-spa-loreal",                  category: "Hair Spa", price: 300, duration: 45, description: "Luxurious L'Oréal spa for shine and manageability.",             image_url: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80", featured: true,  sort_order: 12 },
  { id: "13", name: "Hair Spa – L'Oréal Treatment",       slug: "hair-spa-loreal-treatment",        category: "Hair Spa", price: 350, duration: 60, description: "Premium L'Oréal treatment spa for intense restoration.",        image_url: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80", featured: false, sort_order: 13 },
  { id: "14", name: "Hair Spa – Schwarzkopf",             slug: "hair-spa-schwarzkopf",             category: "Hair Spa", price: 350, duration: 45, description: "Professional Schwarzkopf spa for healthy, vibrant hair.",        image_url: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80", featured: false, sort_order: 14 },
  { id: "15", name: "Hair Spa – Schwarzkopf Treatment",   slug: "hair-spa-schwarzkopf-treatment",   category: "Hair Spa", price: 400, duration: 60, description: "Elite Schwarzkopf treatment spa for ultimate hair revival.",    image_url: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80", featured: false, sort_order: 15 },

  // ── Hair Colour ────────────────────────────────────────────────────────────
  { id: "16", name: "Hair Colour – Matrix",              slug: "hair-colour-matrix",              category: "Hair Colour", price: 250, duration: 60, description: "Vibrant Matrix colour for a bold, lasting transformation.",      image_url: "https://images.unsplash.com/photo-1598524997937-b9c4bc2fa0dd?w=600&q=80", featured: true,  sort_order: 16 },
  { id: "17", name: "Hair Colour – L'Oréal",            slug: "hair-colour-loreal",              category: "Hair Colour", price: 300, duration: 60, description: "Rich L'Oréal colour with fade-resistant shine.",               image_url: "https://images.unsplash.com/photo-1598524997937-b9c4bc2fa0dd?w=600&q=80", featured: false, sort_order: 17 },
  { id: "18", name: "Hair Colour – Schwarzkopf",        slug: "hair-colour-schwarzkopf",         category: "Hair Colour", price: 350, duration: 60, description: "Professional Schwarzkopf colour for intense depth.",           image_url: "https://images.unsplash.com/photo-1598524997937-b9c4bc2fa0dd?w=600&q=80", featured: false, sort_order: 18 },
  { id: "19", name: "Hair Colour – L'Oréal Inoa",       slug: "hair-colour-loreal-inoa",         category: "Hair Colour", price: 350, duration: 75, description: "Ammonia-free Inoa colour — gentle, vivid and long-lasting.",    image_url: "https://images.unsplash.com/photo-1598524997937-b9c4bc2fa0dd?w=600&q=80", featured: false, sort_order: 19 },
  { id: "20", name: "Hair Colour – Matrix No Ammonia",  slug: "hair-colour-matrix-no-ammonia",   category: "Hair Colour", price: 300, duration: 60, description: "Gentle ammonia-free Matrix formula for sensitive scalps.",    image_url: "https://images.unsplash.com/photo-1598524997937-b9c4bc2fa0dd?w=600&q=80", featured: false, sort_order: 20 },
  { id: "21", name: "Hair Colour – Schwarzkopf Essensity", slug: "hair-colour-schwarzkopf-essensity", category: "Hair Colour", price: 400, duration: 75, description: "Oil-based Essensity colour — pure, natural and nourishing.", image_url: "https://images.unsplash.com/photo-1598524997937-b9c4bc2fa0dd?w=600&q=80", featured: false, sort_order: 21 },

  // ── Beard Colour ───────────────────────────────────────────────────────────
  { id: "22", name: "Beard Colour – Bigen",  slug: "beard-colour-bigen", category: "Beard Colour", price: 200, duration: 30, description: "Premium Bigen beard colour for a natural, even finish.", image_url: "https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=600&q=80", featured: false, sort_order: 22 },
  { id: "23", name: "Beard Colour",          slug: "beard-colour",       category: "Beard Colour", price: 100, duration: 20, description: "Standard beard colouring to cover greys effortlessly.",  image_url: "https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=600&q=80", featured: false, sort_order: 23 },

  // ── Hair Treatment ─────────────────────────────────────────────────────────
  { id: "24", name: "Hair Smoothing / Rebonding – Short to Medium", slug: "smoothing-short",       category: "Hair Treatment", price: 800,  duration: 120, description: "Smoothing/rebonding for short to medium length hair.",        image_url: "https://images.unsplash.com/photo-1512690459411-b9245aed614b?w=600&q=80", featured: true,  sort_order: 24 },
  { id: "25", name: "Hair Smoothing / Rebonding – Medium to Neck",  slug: "smoothing-medium",      category: "Hair Treatment", price: 1100, duration: 150, description: "Smoothing/rebonding for medium to neck length hair.",        image_url: "https://images.unsplash.com/photo-1512690459411-b9245aed614b?w=600&q=80", featured: false, sort_order: 25 },
  { id: "26", name: "Hair Keratin – Short to Medium",               slug: "keratin-short",         category: "Hair Treatment", price: 1000, duration: 120, description: "Keratin treatment for silky smooth short to medium hair.",    image_url: "https://images.unsplash.com/photo-1512690459411-b9245aed614b?w=600&q=80", featured: true,  sort_order: 26 },
  { id: "27", name: "Hair Keratin – Medium to Neck",                slug: "keratin-medium",        category: "Hair Treatment", price: 1500, duration: 150, description: "Keratin treatment for medium to neck length hair.",          image_url: "https://images.unsplash.com/photo-1512690459411-b9245aed614b?w=600&q=80", featured: false, sort_order: 27 },
  { id: "28", name: "Hair Botox – Short to Medium",                 slug: "botox-short",           category: "Hair Treatment", price: 1000, duration: 120, description: "Botox treatment for frizz-free, rejuvenated short hair.",    image_url: "https://images.unsplash.com/photo-1512690459411-b9245aed614b?w=600&q=80", featured: false, sort_order: 28 },
  { id: "29", name: "Hair Botox – Medium to Neck",                  slug: "botox-medium",          category: "Hair Treatment", price: 1500, duration: 150, description: "Botox treatment for medium to neck length hair.",           image_url: "https://images.unsplash.com/photo-1512690459411-b9245aed614b?w=600&q=80", featured: false, sort_order: 29 },

  // ── Hair Curling & Perm ────────────────────────────────────────────────────
  { id: "30", name: "Hair Curling – Short Hair",          slug: "curling-short",         category: "Hair Curling & Perm", price: 1000, duration: 90,  description: "Beautiful curls for short hair.",                              image_url: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=600&q=80", featured: false, sort_order: 30 },
  { id: "31", name: "Hair Perm Tight – Medium Length",    slug: "perm-tight-medium",     category: "Hair Curling & Perm", price: 1300, duration: 120, description: "Tight perm curls for medium length hair.",                    image_url: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=600&q=80", featured: false, sort_order: 31 },
  { id: "32", name: "Hair Perm Loose – Medium Length",    slug: "perm-loose-medium",     category: "Hair Curling & Perm", price: 1500, duration: 120, description: "Loose, natural perm waves for medium length hair.",           image_url: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=600&q=80", featured: false, sort_order: 32 },
  { id: "33", name: "Hair Perm Loose – Neck Length",      slug: "perm-loose-neck",       category: "Hair Curling & Perm", price: 2000, duration: 150, description: "Flowing loose perm waves for neck length hair.",              image_url: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=600&q=80", featured: false, sort_order: 33 },

  // ── Styling ────────────────────────────────────────────────────────────────
  { id: "34", name: "Hair Styling", slug: "hair-styling", category: "Styling", price: 100, duration: 20, description: "Expert styling for any occasion — sleek, textured or voluminous.", image_url: "https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=600&q=80", featured: false, sort_order: 34 },

  // ── Facial & Clean-Up ──────────────────────────────────────────────────────
  { id: "35", name: "Facial – Oxy",     slug: "facial-oxy",     category: "Facial & Clean-Up", price: 700,  duration: 60, description: "Oxygen-infused facial for a bright, refreshed complexion.",       image_url: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80", featured: false, sort_order: 35 },
  { id: "36", name: "Facial – Lotus",   slug: "facial-lotus",   category: "Facial & Clean-Up", price: 900,  duration: 60, description: "Lotus facial for deeply hydrated, glowing skin.",               image_url: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80", featured: true,  sort_order: 36 },
  { id: "37", name: "Facial – O3+",     slug: "facial-o3plus",  category: "Facial & Clean-Up", price: 1500, duration: 75, description: "Advanced O3+ facial targeting anti-aging and deep cleansing.",  image_url: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80", featured: false, sort_order: 37 },
  { id: "38", name: "Facial – Kanpeki", slug: "facial-kanpeki", category: "Facial & Clean-Up", price: 2000, duration: 90, description: "Premium Kanpeki facial for flawless, radiant skin.",             image_url: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80", featured: false, sort_order: 38 },
  { id: "39", name: "Clean-Up – Lotus",   slug: "cleanup-lotus",   category: "Facial & Clean-Up", price: 500, duration: 30, description: "Lotus clean-up for fresh, clear and even skin.",            image_url: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80", featured: false, sort_order: 39 },
  { id: "40", name: "Clean-Up – O3+",     slug: "cleanup-o3plus",  category: "Facial & Clean-Up", price: 700, duration: 30, description: "O3+ clean-up for deep pore cleansing and skin clarity.",    image_url: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80", featured: false, sort_order: 40 },
  { id: "41", name: "Clean-Up – Oxy",     slug: "cleanup-oxy",     category: "Facial & Clean-Up", price: 400, duration: 30, description: "Oxy clean-up for a quick, energising skin refresh.",         image_url: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80", featured: false, sort_order: 41 },
  { id: "42", name: "Clean-Up – Kanpeki", slug: "cleanup-kanpeki", category: "Facial & Clean-Up", price: 900, duration: 45, description: "Kanpeki clean-up for premium skin care and deep cleansing.",  image_url: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80", featured: false, sort_order: 42 },

  // ── Face Care ──────────────────────────────────────────────────────────────
  { id: "43", name: "Face Bleach",               slug: "face-bleach",                category: "Face Care", price: 250, duration: 20, description: "Skin-brightening face bleach for a radiant look.",                image_url: "https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=600&q=80", featured: false, sort_order: 43 },
  { id: "44", name: "Face D-Tan – O3+",          slug: "face-dtan-o3plus",           category: "Face Care", price: 200, duration: 20, description: "O3+ D-Tan pack to reverse sun damage and brighten skin.",        image_url: "https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=600&q=80", featured: false, sort_order: 44 },
  { id: "45", name: "Face D-Tan – Sara",         slug: "face-dtan-sara",             category: "Face Care", price: 150, duration: 20, description: "Sara D-Tan for an even, refreshed complexion.",                  image_url: "https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=600&q=80", featured: false, sort_order: 45 },
  { id: "46", name: "Back Neck D-Tan",           slug: "back-neck-dtan",             category: "Face Care", price: 100, duration: 15, description: "Targeted D-Tan treatment for the back of the neck.",              image_url: "https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=600&q=80", featured: false, sort_order: 46 },
  { id: "47", name: "Face Scrub – O3+",          slug: "face-scrub-o3plus",          category: "Face Care", price: 250, duration: 20, description: "O3+ exfoliating scrub for smoother, cleaner skin.",             image_url: "https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=600&q=80", featured: false, sort_order: 47 },
  { id: "48", name: "Face Scrub – Lotus",        slug: "face-scrub-lotus",           category: "Face Care", price: 200, duration: 20, description: "Gentle Lotus scrub to remove dead skin and impurities.",        image_url: "https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=600&q=80", featured: false, sort_order: 48 },
  { id: "49", name: "Face Scrub – Oxy",          slug: "face-scrub-oxy",             category: "Face Care", price: 150, duration: 15, description: "Oxygen-boosting scrub for vibrant, refreshed skin.",            image_url: "https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=600&q=80", featured: false, sort_order: 49 },
  { id: "50", name: "Face Scrub – Kanpeki",      slug: "face-scrub-kanpeki",         category: "Face Care", price: 250, duration: 20, description: "Kanpeki scrub for deep exfoliation and pore refinement.",       image_url: "https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=600&q=80", featured: false, sort_order: 50 },
  { id: "51", name: "Face Cleansing – Lotus",    slug: "face-cleansing-lotus",       category: "Face Care", price: 200, duration: 20, description: "Lotus cleansing ritual for soft, hydrated skin.",               image_url: "https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=600&q=80", featured: false, sort_order: 51 },
  { id: "52", name: "Face Cleansing – O3+",      slug: "face-cleansing-o3plus",      category: "Face Care", price: 250, duration: 20, description: "Deep O3+ cleansing for pore clarity and radiance.",             image_url: "https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=600&q=80", featured: false, sort_order: 52 },
  { id: "53", name: "Face Cleansing – Kanpeki",  slug: "face-cleansing-kanpeki",     category: "Face Care", price: 250, duration: 20, description: "Kanpeki cleansing for a flawless, balanced complexion.",        image_url: "https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=600&q=80", featured: false, sort_order: 53 },
  { id: "54", name: "Face Cleansing – Oxy",      slug: "face-cleansing-oxy",         category: "Face Care", price: 150, duration: 15, description: "Quick Oxy cleansing to remove impurities and refresh skin.",    image_url: "https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=600&q=80", featured: false, sort_order: 54 },
  { id: "55", name: "Face Steam",                slug: "face-steam",                 category: "Face Care", price: 50,  duration: 10, description: "Soothing face steam to open pores and prep skin.",              image_url: "https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=600&q=80", featured: false, sort_order: 55 },

  // ── Threading & Waxing ─────────────────────────────────────────────────────
  { id: "56", name: "Full Face Threading", slug: "full-face-threading", category: "Threading & Waxing", price: 100,  duration: 20, description: "Complete face threading for clean, defined eyebrows and smooth skin.", image_url: "https://images.unsplash.com/photo-1519500528352-2d1460418d41?w=600&q=80", featured: false, sort_order: 56 },
  { id: "57", name: "Cheeks Threading",    slug: "cheeks-threading",    category: "Threading & Waxing", price: 50,   duration: 10, description: "Targeted cheek threading to remove fine facial hair.",               image_url: "https://images.unsplash.com/photo-1519500528352-2d1460418d41?w=600&q=80", featured: false, sort_order: 57 },
  { id: "58", name: "Face Wax",            slug: "face-wax",            category: "Threading & Waxing", price: 200,  duration: 20, description: "Smooth face waxing for long-lasting hair removal.",                  image_url: "https://images.unsplash.com/photo-1519500528352-2d1460418d41?w=600&q=80", featured: false, sort_order: 58 },
  { id: "59", name: "Nose Wax",            slug: "nose-wax",            category: "Threading & Waxing", price: 50,   duration: 10, description: "Quick and effective nose wax for clear nostrils.",                   image_url: "https://images.unsplash.com/photo-1519500528352-2d1460418d41?w=600&q=80", featured: false, sort_order: 59 },
  { id: "60", name: "Cheeks Wax",          slug: "cheeks-wax",          category: "Threading & Waxing", price: 100,  duration: 15, description: "Gentle cheek waxing for smooth, hair-free skin.",                   image_url: "https://images.unsplash.com/photo-1519500528352-2d1460418d41?w=600&q=80", featured: false, sort_order: 60 },
  { id: "61", name: "Arm Wax",             slug: "arm-wax",             category: "Threading & Waxing", price: 500,  duration: 30, description: "Full arm waxing for silky smooth skin.",                           image_url: "https://images.unsplash.com/photo-1519500528352-2d1460418d41?w=600&q=80", featured: false, sort_order: 61 },
  { id: "62", name: "Body Wax",            slug: "body-wax",            category: "Threading & Waxing", price: 1200, duration: 60, description: "Full body waxing for complete, lasting smoothness.",                image_url: "https://images.unsplash.com/photo-1519500528352-2d1460418d41?w=600&q=80", featured: false, sort_order: 62 },

  // ── Arm & Body Care ────────────────────────────────────────────────────────
  { id: "63", name: "Arm D-Tan",           slug: "arm-dtan",            category: "Arm & Body Care", price: 400, duration: 20, description: "D-Tan treatment for even, sun-damage-free arm skin.",        image_url: "https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?w=600&q=80", featured: false, sort_order: 63 },
  { id: "64", name: "Arm Bleach",          slug: "arm-bleach",          category: "Arm & Body Care", price: 400, duration: 20, description: "Brightening arm bleach for lighter, glowing skin.",          image_url: "https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?w=600&q=80", featured: false, sort_order: 64 },
  { id: "65", name: "Full Body Hair Trim", slug: "full-body-hair-trim", category: "Arm & Body Care", price: 400, duration: 40, description: "Complete body hair trimming for a clean, groomed look.",     image_url: "https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?w=600&q=80", featured: false, sort_order: 65 },
  { id: "66", name: "Half Body Hair Trim", slug: "half-body-hair-trim", category: "Arm & Body Care", price: 300, duration: 25, description: "Half body hair trim for targeted grooming.",                 image_url: "https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?w=600&q=80", featured: false, sort_order: 66 },
  { id: "67", name: "Arm Hair Trim",       slug: "arm-hair-trim",       category: "Arm & Body Care", price: 100, duration: 15, description: "Quick arm hair trimming for a neat appearance.",             image_url: "https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?w=600&q=80", featured: false, sort_order: 67 },

  // ── Manicure & Pedicure ────────────────────────────────────────────────────
  { id: "68", name: "Manicure", slug: "manicure", category: "Manicure & Pedicure", price: 400, duration: 40, description: "Complete manicure — soak, shape, cuticle care and moisturize.", image_url: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=600&q=80", featured: false, sort_order: 68 },
  { id: "69", name: "Pedicure", slug: "pedicure", category: "Manicure & Pedicure", price: 400, duration: 50, description: "Relaxing pedicure for soft, refreshed and pampered feet.",       image_url: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=600&q=80", featured: false, sort_order: 69 },
];

export const fallbackStylists: Stylist[] = [
  { id: "1", name: "Zara M.",  photo_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80", experience: "8 years",  specialization: "Balayage & Color",    bio: "Zara brings artistry and precision to every color service, creating looks that turn heads wherever you go.", availability: "Tue–Sun", instagram: "", facebook: "" },
  { id: "2", name: "Damon K.", photo_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80", experience: "6 years",  specialization: "Precision Cuts",      bio: "Damon is obsessed with the perfect silhouette. His architectural cuts speak for themselves.",                  availability: "Tue–Sun", instagram: "", facebook: "" },
  { id: "3", name: "Isla R.",  photo_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80", experience: "10 years", specialization: "Treatments & Texture", bio: "Isla transforms damaged hair into healthy, luminous locks with her restorative techniques.",                    availability: "Tue–Sat", instagram: "", facebook: "" },
];

export const fallbackGallery: GalleryItem[] = [
  { id: "1",  image_url: "https://images.unsplash.com/photo-1562322140-8baeececf3df?w=600&q=80", caption: "Blonde balayage transformation",  category: "Color",              sort_order: 1  },
  { id: "2",  image_url: "https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=600&q=80", caption: "Precision cut and style",      category: "Haircut",            sort_order: 2  },
  { id: "3",  image_url: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80", caption: "Our premium salon space",        category: "Interior",           sort_order: 3  },
  { id: "4",  image_url: "https://images.unsplash.com/photo-1598524997937-b9c4bc2fa0dd?w=600&q=80", caption: "Rich color transformation",   category: "Color",              sort_order: 4  },
  { id: "5",  image_url: "https://images.unsplash.com/photo-1634449571010-02389ed0f9b0?w=600&q=80", caption: "Expert styling session",      category: "Style",              sort_order: 5  },
  { id: "6",  image_url: "https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?w=600&q=80", caption: "Beachy waves finish",         category: "Style",              sort_order: 6  },
  { id: "7",  image_url: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80", caption: "Deep conditioning treatment", category: "Treatment",          sort_order: 7  },
  { id: "8",  image_url: "https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=600&q=80", caption: "Blowout perfection",          category: "Style",              sort_order: 8  },
  { id: "9",  image_url: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=600&q=80", caption: "Stylist at work",             category: "Behind the Scenes",  sort_order: 9  },
  { id: "10", image_url: "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=600&q=80", caption: "Salon styling station",       category: "Interior",           sort_order: 10 },
  { id: "11", image_url: "https://images.unsplash.com/photo-1519500528352-2d1460418d41?w=600&q=80", caption: "Welcoming reception",         category: "Interior",           sort_order: 11 },
  { id: "12", image_url: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80", caption: "Relaxing hair spa",           category: "Treatment",          sort_order: 12 },
  { id: "13", image_url: "https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=600&q=80", caption: "Beard grooming",              category: "Grooming",           sort_order: 13 },
];

export const fallbackReviews: Review[] = [
  { id: "1", name: "Sarah L.",  rating: 5, review: "Best haircut I've ever had. Zara understood exactly what I wanted and delivered something even better. I won't go anywhere else.",              photo_url: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80", created_at: new Date().toISOString() },
  { id: "2", name: "Marcus T.", rating: 5, review: "Damon is a genius with scissors. My hair has never looked this good. The whole experience felt premium from start to finish.",                  photo_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80", created_at: new Date().toISOString() },
  { id: "3", name: "Priya K.",  rating: 5, review: "The balayage came out absolutely perfect. Natural, dimensional, exactly what I pictured. I get compliments every single day.",                 photo_url: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&q=80", created_at: new Date().toISOString() },
  { id: "4", name: "Rohan S.",  rating: 5, review: "Got the keratin treatment done — my hair is incredibly smooth now. Worth every rupee. The staff is very friendly and professional.",           photo_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&q=80", created_at: new Date().toISOString() },
  { id: "5", name: "Meera V.",  rating: 5, review: "Came in for a hair spa and left feeling completely rejuvenated. The salon is so clean and the ambience is amazing.",                           photo_url: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&q=80", created_at: new Date().toISOString() },
];
